Remove Trailing spaces.
git-svn-id: file:///srv/svn/reactos/trunk@30964 97493ccd-5924-5043-b1f5-66cb403b36ce

diff --git a/tools/RosBE/RosBE-PPC/ovr/make b/tools/RosBE/RosBE-PPC/ovr/make
--- a/tools/RosBE/RosBE-PPC/ovr/make
+++ b/tools/RosBE/RosBE-PPC/ovr/make
@@ -3,7 +3,7 @@
 export PATH=tools/ppc.lost+found:$PATH
 
 if [ ! -d tmp-ppc ] ; then
-	mkdir tmp-ppc || echo "Could not make temp dir" 
+	mkdir tmp-ppc || echo "Could not make temp dir"
 fi
 
 $OLDMAKE \
